env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - RGL_USE_NULL=TRUE

language: r
sudo: false
cache: packages
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

r_github_packages:
  - r-lib/covr
  - benkeser/halplus

# coverage
after_success:
  - Rscript -e 'covr::codecov()'

script:
  - |
    R CMD build --no-build-vignettes .
    travis_wait 60 R CMD check --no-build-vignettes hal9001*tar.gz

notifications:
  email:
    on_success: change
    on_failure: change

