branches:
  only:
    - master
    - devel

env:
  global:
    - RGL_USE_NULL=TRUE

language: r
sudo: required
cache: packages
warnings_are_errors: true

cran: https://cran.rstudio.com
r_build_args: '--no-manual'
r_check_args: '--no-build-vignettes --no-manual'

r:
  - release
  - devel

r_packages:
  - devtools
  - covr

r_github_packages:
  - r-lib/covr
  - r-lib/sessioninfo

# coverage
after_success:
  - travis_wait 60 Rscript -e 'covr::codecov()'

on_failure:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change
